language: ruby
rvm:
- "1.9.3"
- "2.0"
- "2.1"
- "2.2"
- ruby-head
- jruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
before_script: bundle exec rake db:setup
